import type { editor } from 'monaco-editor';

export const CEditConfig: editor.IStandaloneEditorConstructionOptions = {
  acceptSuggestionOnCommitCharacter: true,
  // acceptSuggestionOnEnter: 'on',
  // accessibilitySupport: 'auto',
  // autoIndent: false,
  automaticLayout: true,
  codeLens: true,
  colorDecorators: true,
  contextmenu: true,
  // cursorBlinking: 'blink',
  cursorSmoothCaretAnimation: 'off',
  // cursorStyle: 'line',
  disableLayerHinting: false,
  disableMonospaceOptimizations: false,
  dragAndDrop: false,
  fixedOverflowWidgets: false,
  folding: true,
  // foldingStrategy: 'auto',
  fontLigatures: false,
  formatOnPaste: false,
  formatOnType: false,
  hideCursorInOverviewRuler: false,
  links: true,
  mouseWheelZoom: false,
  multiCursorMergeOverlapping: true,
  // multiCursorModifier: 'alt',
  overviewRulerBorder: true,
  overviewRulerLanes: 2,
  quickSuggestions: false,
  quickSuggestionsDelay: 100,
  readOnly: false,
  renderControlCharacters: false,
  renderFinalNewline: 'on',
  // highlightActiveIndentGuide: true,
  // renderIndentGuides: true,
  guides: {
    highlightActiveIndentation: true,
    indentation: true,
  },
  // renderLineHighlight: 'all',
  // renderWhitespace: 'none',
  revealHorizontalRightPadding: 30,
  roundedSelection: true,
  rulers: [],
  scrollBeyondLastColumn: 5,
  scrollBeyondLastLine: true,
  selectOnLineNumbers: true,
  selectionClipboard: true,
  selectionHighlight: true,
  // showFoldingControls: 'mouseover',
  smoothScrolling: false,
  suggestOnTriggerCharacters: true,
  wordBasedSuggestions: true,
  wordSeparators: "~!@#$%^&*()-=+[{]}|;:',.<>/?",
  // wordWrap: 'off',
  wordWrapBreakAfterCharacters: ' \t})]?|&,;',
  wordWrapBreakBeforeCharacters: ' {([+',
  // wordWrapBreakObtrusiveCharacters: '.',
  wordWrapColumn: 80,
  // wordWrapMinified: true,
  // wrappingIndent: "none"
};
